categories:
  Treats:
    ChompStars:
      info: "Neon-colored crunchies that glow faintly in the dark. Possibly radioactive. Pets love them."
      price: 2.00
    Happy Liver Bites:
      info: "Shaped like smiling faces. No one knows what liver they’re made from."
      price: 3.50
    Dream Jerky:
      info: "Only visible to the pet. Smells like childhood."
      price: 3.00
    Meat Candy:
      info: "Too sweet. Like... unnaturally sweet. Pet becomes hyper for 3 minutes."
      price: 5.00

  Diet:
    SlimTail Mix:
      info: "Suppresses hunger and emotion. Especially useful during shedding season."
      price: 5.20
    BlankBites:
      info: "Tasteless cubes. Technically food. Nothing more."
      price: 6.00
    Calm Crunch:
      info: "Prevents overeating, but might cause existential detachment."
      price: 7.50
    PurgePaste:
      info: "Cleanses body and memory. Used in cult facilities."
      price: 5.50

  Organic:
    RootSnax:
      info: "Made from dreamroot. Occasionally whispers."
      price: 10.00
    FreeRoam Hearts:
      info: "Ethically sourced from animals who volunteered."
      price: 12.00
    MossMelt Loaf:
      info: "Soft, warm, and slightly sentient. Grows back if not finished."
      price: 11.50
    Sunfruit Morsels:
      info: "Each bite feels like being watched by the sun."
      price: 10.50

  Supplements:
    MoodMod Pills:
      info: "Regulates pet's emotional spectrum. Can induce artificial love."
      price: 3.00
    VitaSprout Tabs:
      info: "Grows glowing flowers in the pet’s stomach for \"internal harmony.\""
      price: 4.50
    IronHowl Dust:
      info: "Strengthens bones and encourages midnight screaming."
      price: 5.00
    NULL Chews:
      info: "Eliminates 1 random weakness. Also eliminates... something else."
      price: 6.00
